### ISSUE TITLE
Workflow 7 Error: [NodeId: Calibration_400] DSD not found

### ISSUE THREAD

**Issue by j08lue** [GlobWetlandAfrica/GWA_models_and_workflows#1]
From @hubersi:

We are trying to run workflow 7, Lake Tana example from Ethiopia with ASAR data. We can do step 1 and 2 of 01a preprocessing, but step 3 doesn’t work. The file is not written.

The output from step 2 is attached: [01a_step2.data.zip](https://github.com/GlobWetlandAfricaIII/GWA_models_and_workflows/files/985743/01a_step2.data.zip).

The traceback is:

```
2017-05-08T21:00:40	0	GPF Graph
			<graph id="Calibration_gpf">
			  <version>1.0</version>
			  <node id="Calibration_400_read_402">
			    <operator>Read</operator>
			    <sources />
			    <parameters>
			      <file>C:/data/GRAS/EO4SD_Agriculture/Ethiopia/SAWAP_WB_SLMP2/DEMO/DEMO_RABAT/PG07_Flood_mapping_system/DC21/Demo_May17/01a_step2.dim</file>
			    </parameters>
			  </node>
			  <node id="Calibration_400">
			    <operator>Calibration</operator>
			    <sources>
			      <sourceProduct refid="Calibration_400_read_402" />
			    </sources>
			    <parameters>
			      <selectedPolarisations />
			      <sourceBands>Amplitude</sourceBands>
			      <auxFile>Product Auxiliary File</auxFile>
			      <externalAuxFile />
			      <outputImageInComplex>False</outputImageInComplex>
			      <outputImageScaleInDb>True</outputImageScaleInDb>
			      <outputGammaBand>False</outputGammaBand>
			      <createGammaBand>False</createGammaBand>
			      <outputBetaBand>False</outputBetaBand>
			      <createBetaBand>False</createBetaBand>
			      <outputSigmaBand>True</outputSigmaBand>
			    </parameters>
			  </node>
			  <node id="Calibration_400_write_403">
			    <operator>Write</operator>
			    <sources>
			      <sourceProduct refid="Calibration_400" />
			    </sources>
			    <parameters>
			      <file>C:/data/GRAS/EO4SD_Agriculture/Ethiopia/SAWAP_WB_SLMP2/DEMO/DEMO_RABAT/PG07_Flood_mapping_system/DC21/Demo_May17/01a_step3.dim</file>
			      <formatName>BEAM-DIMAP</formatName>
			    </parameters>
			  </node>
			</graph>
2017-05-08T21:00:47	0	SNAP execution console output
			"C:\Program Files\snap\bin\gpt" "c:\users\shu\appdata\local\temp\gpf.xml" -e -q 4
			INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Loading external tools...
			
			INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Scanning for external tools adapters: C:\Program Files\snap\s3tbx
			
			INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Scanning for external tools adapters: C:\Program Files\snap\rstb
			
			INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Scanning for external tools adapters: C:\Program Files\snap\s2tbx
			
			INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Scanning for external tools adapters: C:\Program Files\snap\java
			
			SEVERE: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Failed scan for Tools descriptors: I/O problem: C:\Program Files\snap\java
			
			DSD not found
			
			org.esa.snap.core.gpf.graph.GraphException: [NodeId: Calibration_400] DSD not found
			
				at org.esa.snap.core.gpf.graph.NodeContext.initTargetProduct(NodeContext.java:79)
			
				at org.esa.snap.core.gpf.graph.GraphContext.initNodeContext(GraphContext.java:195)
			
				at org.esa.snap.core.gpf.graph.GraphContext.initNodeContext(GraphContext.java:178)
			
				at org.esa.snap.core.gpf.graph.GraphContext.initOutput(GraphContext.java:162)
			
				at org.esa.snap.core.gpf.graph.GraphContext.<init>(GraphContext.java:91)
			
				at org.esa.snap.core.gpf.graph.GraphContext.<init>(GraphContext.java:64)
			
				at org.esa.snap.core.gpf.graph.GraphProcessor.executeGraph(GraphProcessor.java:130)
			
				at org.esa.snap.core.gpf.main.DefaultCommandLineContext.executeGraph(DefaultCommandLineContext.java:84)
			
				at org.esa.snap.core.gpf.main.CommandLineTool.executeGraph(CommandLineTool.java:498)
			
				at org.esa.snap.core.gpf.main.CommandLineTool.runGraph(CommandLineTool.java:346)
			
				at org.esa.snap.core.gpf.main.CommandLineTool.runGraphOrOperator(CommandLineTool.java:245)
			
				at org.esa.snap.core.gpf.main.CommandLineTool.run(CommandLineTool.java:146)
			
				at org.esa.snap.core.gpf.main.CommandLineTool.run(CommandLineTool.java:118)
			
				at org.esa.snap.core.gpf.main.GPT.run(GPT.java:54)
			
				at org.esa.snap.core.gpf.main.GPT.main(GPT.java:34)
			
				at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			
				at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
			
				at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
			
				at java.lang.reflect.Method.invoke(Unknown Source)
			
				at org.esa.snap.runtime.Launcher.lambda$run$0(Launcher.java:55)
			
				at org.esa.snap.runtime.Engine.runClientCode(Engine.java:189)
			
				at org.esa.snap.runtime.Launcher.run(Launcher.java:51)
			
				at org.esa.snap.runtime.Launcher.main(Launcher.java:31)
			
				at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			
				at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
			
				at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
			
				at java.lang.reflect.Method.invoke(Unknown Source)
			
				at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:62)
			
				at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:101)
			
				at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:26)
			
			Caused by: org.esa.snap.core.gpf.OperatorException: DSD not found
			
				at org.esa.snap.engine_utilities.gpf.OperatorUtils.catchOperatorException(OperatorUtils.java:421)
			
				at org.esa.s1tbx.calibration.gpf.CalibrationOp.initialize(CalibrationOp.java:159)
			
				at org.esa.snap.core.gpf.internal.OperatorContext.initializeOperator(OperatorContext.java:486)
			
				at org.esa.snap.core.gpf.internal.OperatorContext.getTargetProduct(OperatorContext.java:273)
			
				at org.esa.snap.core.gpf.Operator.getTargetProduct(Operator.java:387)
			
				at org.esa.snap.core.gpf.graph.NodeContext.initTargetProduct(NodeContext.java:77)
			
				... 29 more
			
			
			
			Error: [NodeId: Calibration_400] DSD not found
```

**Comment by j08lue** [comment]
So what happens is that the SNAP Calibration algorithm fails because it is missing some DSD – what is DSD and why is it missing? Any leads, @radosuav? 😎 Does this sound familiar, @ctottrup?

**Comment by j08lue** [comment]
So [DSD](https://github.com/umwilm/snap-engine/blob/master/beam-envisat-reader/src/main/java/org/esa/beam/dataio/envisat/DSD.java#L22) is the
>  data set descriptor (DSD) found in the specific product header (SPH) of MERIS level 1b

Could it be that the DSD is missing from the DIM file for some reason?

**Comment by radosuav** [comment]
The discussion should move to https://github.com/TIGER-NET/WOIS_models_and_workflows/issues/1 since this is a TIGER-NET workflow issue.

**Comment by j08lue** [comment]
Issue closed. See details at https://github.com/TIGER-NET/WOIS_models_and_workflows/issues/1
