### ISSUE TITLE
Sentinel download fails

### ISSUE THREAD

**Issue by ctottrup** [GlobWetlandAfrica/GWA_models_and_workflows#3]
Uncaught error while executing algorithm
			Traceback (most recent call last):
			  File "C:/Users/cto/.qgis2/python/plugins\processing\core\GeoAlgorithm.py", line 203, in execute
			    self.processAlgorithm(progress)
			  File "C:/Users/cto/.qgis2/python/plugins\processing\script\ScriptAlgorithm.py", line 378, in processAlgorithm
			    exec((script), ns)
			  File "<string>", line 31, in <module>
			  File "C:\Users\cto\.qgis2\processing\scripts\sentinel_download\sentinel_download\api.py", line 58, in query
			    r = self.open_url(self.url)
			  File "C:\Users\cto\.qgis2\processing\scripts\sentinel_download\sentinel_download\api.py", line 46, in open_url
			    'Check the URL and download parameters and try again!'.format(r.status_code, url))
			RuntimeError: HTTP Error: 504 for URL: 'https://scihub.copernicus.eu/apihub/search?format=json&rows=100&start=0&q=(beginPosition:[2017-05-08T15:43:38Z+TO+2017-05-18T15:43:38Z])+AND+(footprint:"Intersects(POLYGON((33.8204613842+12.4671514544,38.0330992979+12.4671514544,38.0330992979+16.2901203611,33.8204613842+16.2901203611,33.8204613842+12.4671514544)))")+AND+(platformname:"Sentinel-1")'. Check the URL and download parameters and try again!

**Comment by j08lue** [comment]
Could be a temporary outage on SciHub, because the link works for me right now.

**Comment by j08lue** [comment]
And the script works, too, this morning. Please try again.

**Comment by ctottrup** [comment]
Working here a well this morning ;-)
