### ISSUE TITLE
NDVI statistics not working

### ISSUE THREAD

**Issue by j08lue** [GlobWetlandAfrica/GWA_models_and_workflows#5]
From @sun0601:

> I found that the model “NDVI statistics - Sentinel”, “NDVI statistics - Landsat” and “pca texture” did not work properly in the newly installed package. I ran into some errors (and the errors are similar for these models), but they worked well when I used the old version. I attach the log messages for running NDVI statistics – Sentinel, could you please help me to figure out what was wrong?

```
2017-05-24T06:17:41	0	OTB execution command
			\otbcli_BandMath
			-il
			"NNN\S2_20160910.tif " "NNN\S2_20161030.tif "
			-ram
			512
			-exp
			((im1b7-im1b3)/(im1b7+im1b3)+(im2b7-im2b3)/(im2b7+im2b3))*500
			-out
			"NNN\AppData\Local\Temp\processing05c58896838a4000ae84bdcf0e0db423\9736b19fae884cb4b95d22ba33ba8973\out.tif"
2017-05-24T06:17:41	0	Adapter for adaptBandMath not found
2017-05-24T06:17:41	0	OTB execution console output
			'"\otbcli_BandMath"' is not recognized as an internal or external command,
			
			operable program or batch file.
			
2017-05-24T06:17:41	0	OTB execution command
			\otbcli_BandMath
			-il
			"NNN\S2_20160910.tif " "NNN\S2_20161030.tif "
			-ram
			512
			-exp
			((im1b7-im1b3)/(im1b7+im1b3)-(im2b7-im2b3)/(im2b7+im2b3))*1000
			-out
			"NNN\AppData\Local\Temp\processing05c58896838a4000ae84bdcf0e0db423\9194369ffac94c62af65150bc695bd36\out.tif"
2017-05-24T06:17:41	0	Adapter for adaptBandMath not found
2017-05-24T06:17:41	0	OTB execution console output
			'"\otbcli_BandMath"' is not recognized as an internal or external command,
			
			operable program or batch file.
			
2017-05-24T06:17:41	0	GDAL execution console output
			ERROR 4: `NNN\AppData\Local\Temp\processing05c58896838a4000ae84bdcf0e0db423\9736b19fae884cb4b95d22ba33ba8973\out.tif' does not exist in the file system,
			
			and is not recognized as a supported dataset name.
			
			
			
			ERROR 4: `NNN\AppData\Local\Temp\processing05c58896838a4000ae84bdcf0e0db423\9194369ffac94c62af65150bc695bd36\out.tif' does not exist in the file system,
			
			and is not recognized as a supported dataset name.
			
			
			
			Traceback (most recent call last):
			
			  File "C:\OSGEO4~1\bin\gdal_merge.py", line 540, in <module>
			
			    sys.exit(main())
			
			  File "C:\OSGEO4~1\bin\gdal_merge.py", line 422, in main
			
			    ulx = file_infos[0].ulx
			
			IndexError: list index out of range
			
2017-05-24T06:17:41	2	Error loading result layer:
			Traceback (most recent call last):
			  File "NNN/.qgis2/python/plugins\processing\gui\Postprocessing.py", line 75, in handleAlgorithmResults
			    out.name))
			  File "NNN/.qgis2/python/plugins\processing\tools\dataobjects.py", line 199, in load
			    + '\nCheck the processing framework log to look for errors')
			RuntimeError: Could not load layer: D:/ndvistats.tif
			Check the processing framework log to look for errors
			
```

**Comment by j08lue** [comment]
I guess the original problem here was with OTB: `Adapter for adaptBandMath not found`.

I will try to reproduce the error and get back to you.

**Comment by j08lue** [comment]
@sun0601 - Do we still have this issue?

**Comment by sun0601** [comment]
No, after I re-install the package there is no problem with the tool.

**Comment by j08lue** [comment]
Excellent, thanks.
