### ISSUE TITLE
Error in I/O workflow - Calculate Landsat Indices

### ISSUE THREAD

**Issue by 01zeng** [GlobWetlandAfrica/GWA_models_and_workflows#59]
Hi, 

I am beginner using the Globwetland toolbox. Everytime that I want to calculate landsat indices, there is a message error appearing. Here is the error message : invalid value encountered in divide See log for more details. 
Here a screenshot: 
![image](https://user-images.githubusercontent.com/84041046/117869409-0ea06600-b29b-11eb-80a3-a642f45e5a76.png)
the message in log : 
ncaught error while executing algorithm
			Traceback (most recent call last):
			  File "C:/Users/senghor/.qgis2/python/plugins\processing\core\GeoAlgorithm.py", line 203, in execute
			    self.processAlgorithm(progress)
			  File "C:/Users/senghor/.qgis2/python/plugins\processing\script\ScriptAlgorithm.py", line 381, in processAlgorithm
			    exec((script), ns)
			  File "<string>", line 22, in <module>
			  File "C:\Users\senghor\.qgis2\processing\scripts\generic_tools\landsat_indices.py", line 42, in landsat_indices
			    ndvi = calc_index(stk, 4, 3)
			  File "C:\Users\senghor\.qgis2\processing\scripts\generic_tools\landsat_indices.py", line 24, in calc_index
			    any_index = standard_index(band1, band2)
			  File "C:\Users\senghor\.qgis2\processing\scripts\generic_tools\landsat_indices.py", line 10, in standard_index
			    idx = (band1 - band2) / (band1 + band2) * 10000
			FloatingPointError: invalid value encountered in divide

would you help in any tips or guidance, i'm stuck and cannot proceed further for the next workflows. 

For your information, I am working with landsat 7 image.

**Comment by j08lue** [comment]
This is a division-by-zero error. So the expression `band1 + band2` of the index calculation at least in some pixels results in zero. Ideally, you should be getting `NaN` in those points instead and that is normally the [default behavior of Numpy](https://numpy.org/devdocs/user/misc.html): to warn, not raise in the case of division by zero.

You could try to open the Python command prompt in QGIS and type the following:

```python
import numpy as np
np.seterr(divide='warn')
```

But I am not sure the script runs in the same shell and will pick up that setting. Alternatively, you can open the script file and add the same lines to the top of the file.

**Comment by 01zeng** [comment]
Issue fixed. I have added the lines directly into the script. 
Many Thanks
